### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by VuzzyM** [naiba/twitter2telegram#1]
Hello. 

What is telegram admin id?

On this format put @username account telegram or how?

**Comment by naiba** [comment]
Use @userinfobot to get your user id

**Comment by VuzzyM** [comment]
> Use userinfobot to get your user id

User not authorized, please contact administrator to add permissions, not working

**Comment by VuzzyM** [comment]
> > Use userinfobot to get your user id
> 
> User not authorized, please contact administrator to add permissions, not working

@naiba ?

**Comment by naiba** [comment]
Put your id in the config file.

TELEGRAM_ADMIN_ID=your id

Then restart the container.

**Comment by naiba** [comment]
Put your id in the config file.

TELEGRAM_ADMIN_ID=your id

Then restart the container.

**Comment by VuzzyM** [comment]
> Put your id in the config file.
> 
> TELEGRAM_ADMIN_ID=your id
> 
> Then restart the container.

I did this.

docker-compose stop and docker-compose start

**Comment by naiba** [comment]
> > Put your id in the config file.
> > TELEGRAM_ADMIN_ID=your id
> > Then restart the container.
> 
> I did this.
> 
> docker-compose stop and docker-compose start, not working

Are you renamed .env.example to .env?
Ensure your volume binding `.env` is a file, not a folder.

**Comment by VuzzyM** [comment]
> LOL, I got it, you need to submit in the bot use "/AddUser" to add yourself as a user

I'll try this later, I'm not on the PC now

**Comment by VuzzyM** [comment]
> LOL, I got it, you need to submit in the bot use "/AddUser" to add yourself as a user

Also not working, format is this/AddUser and id?

**Comment by VuzzyM** [comment]
> /AddUser id string_label

Hello, is working, thanks. i use this format /AddUser id username. Please add instructions for others in the readme.
