### ISSUE TITLE
Not coming tweets

### ISSUE THREAD

**Issue by VuzzyM** [naiba/twitter2telegram#2]
Hello.

I do not receive any tweets, even if I am subscribed to a channel. What is the problem?

**Comment by naiba** [comment]
You did not successfully subscribe to the Twitter user,

`/FollowTwitterID twitter_user_id_to_subscribe_to 0`

Do this to follow a twitter user.

**Comment by naiba** [comment]
https://github.com/naiba/twitter2telegram/blob/main/src/telegram_bot.rs#L40

All commands are included here, please try them yourself.
